

// AUTO GENERATE CODE START [WIDGETS] --------
#include "widget/Obj.hpp"
#include "widget/AnimImg.hpp"
#include "widget/Btn.hpp"
#include "widget/Canvas.hpp"
#include "widget/Dropdown.hpp"
#include "widget/Keyboard.hpp"
#include "widget/Line.hpp"
#include "widget/MsgBox.hpp"
#include "widget/Scale.hpp"
#include "widget/SpinBox.hpp"
#include "widget/Table.hpp"
#include "widget/TileView.hpp"
#include "widget/Arc.hpp"
#include "widget/BtnMatrix.hpp"
#include "widget/Chart.hpp"
#include "widget/Img.hpp"
#include "widget/Label.hpp"
#include "widget/List.hpp"
#include "widget/Slider.hpp"
#include "widget/Spinner.hpp"
#include "widget/TabView.hpp"
#include "widget/Win.hpp"
#include "widget/Bar.hpp"
#include "widget/Calendar.hpp"
#include "widget/Checkbox.hpp"
#include "widget/ImgBtn.hpp"
#include "widget/Led.hpp"
#include "widget/Menu.hpp"
#include "widget/Roller.hpp"
#include "widget/Span.hpp"
#include "widget/Switch.hpp"
#include "widget/TextArea.hpp"
#include "widget/Gif.hpp"
// AUTO GENERATE CODE END [WIDGETS] --------

#include "ext/Row.hpp"
#include "ext/Column.hpp"
#include "ext/Rect.hpp"
